package com.soecode.lyf.entity;

import java.math.BigDecimal;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.orderId
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.wxopenId
     *
     * @mbggenerated
     */
    private String wxopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.senderName
     *
     * @mbggenerated
     */
    private String sendername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.senderPhone
     *
     * @mbggenerated
     */
    private Integer senderphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.senderAddressId
     *
     * @mbggenerated
     */
    private Integer senderaddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipientName
     *
     * @mbggenerated
     */
    private String recipientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipientPhone
     *
     * @mbggenerated
     */
    private Integer recipientphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recipientAddressId
     *
     * @mbggenerated
     */
    private Integer recipientaddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.isable
     *
     * @mbggenerated
     */
    private Integer isable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.orderId
     *
     * @return the value of order.orderId
     *
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.orderId
     *
     * @param orderid the value for order.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.wxopenId
     *
     * @return the value of order.wxopenId
     *
     * @mbggenerated
     */
    public String getWxopenid() {
        return wxopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.wxopenId
     *
     * @param wxopenid the value for order.wxopenId
     *
     * @mbggenerated
     */
    public void setWxopenid(String wxopenid) {
        this.wxopenid = wxopenid == null ? null : wxopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.senderName
     *
     * @return the value of order.senderName
     *
     * @mbggenerated
     */
    public String getSendername() {
        return sendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.senderName
     *
     * @param sendername the value for order.senderName
     *
     * @mbggenerated
     */
    public void setSendername(String sendername) {
        this.sendername = sendername == null ? null : sendername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.senderPhone
     *
     * @return the value of order.senderPhone
     *
     * @mbggenerated
     */
    public Integer getSenderphone() {
        return senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.senderPhone
     *
     * @param senderphone the value for order.senderPhone
     *
     * @mbggenerated
     */
    public void setSenderphone(Integer senderphone) {
        this.senderphone = senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.senderAddressId
     *
     * @return the value of order.senderAddressId
     *
     * @mbggenerated
     */
    public Integer getSenderaddressid() {
        return senderaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.senderAddressId
     *
     * @param senderaddressid the value for order.senderAddressId
     *
     * @mbggenerated
     */
    public void setSenderaddressid(Integer senderaddressid) {
        this.senderaddressid = senderaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipientName
     *
     * @return the value of order.recipientName
     *
     * @mbggenerated
     */
    public String getRecipientname() {
        return recipientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipientName
     *
     * @param recipientname the value for order.recipientName
     *
     * @mbggenerated
     */
    public void setRecipientname(String recipientname) {
        this.recipientname = recipientname == null ? null : recipientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipientPhone
     *
     * @return the value of order.recipientPhone
     *
     * @mbggenerated
     */
    public Integer getRecipientphone() {
        return recipientphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipientPhone
     *
     * @param recipientphone the value for order.recipientPhone
     *
     * @mbggenerated
     */
    public void setRecipientphone(Integer recipientphone) {
        this.recipientphone = recipientphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recipientAddressId
     *
     * @return the value of order.recipientAddressId
     *
     * @mbggenerated
     */
    public Integer getRecipientaddressid() {
        return recipientaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recipientAddressId
     *
     * @param recipientaddressid the value for order.recipientAddressId
     *
     * @mbggenerated
     */
    public void setRecipientaddressid(Integer recipientaddressid) {
        this.recipientaddressid = recipientaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.weight
     *
     * @return the value of order.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.weight
     *
     * @param weight the value for order.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.amount
     *
     * @return the value of order.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.amount
     *
     * @param amount the value for order.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.status
     *
     * @return the value of order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.status
     *
     * @param status the value for order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.username
     *
     * @return the value of order.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.username
     *
     * @param username the value for order.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.isable
     *
     * @return the value of order.isable
     *
     * @mbggenerated
     */
    public Integer getIsable() {
        return isable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.isable
     *
     * @param isable the value for order.isable
     *
     * @mbggenerated
     */
    public void setIsable(Integer isable) {
        this.isable = isable;
    }
}