package com.soecode.lyf.entity;

import java.util.Date;

public class WxOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.orderId
     *
     * @mbggenerated
     */
    private String orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.wxopenId
     *
     * @mbggenerated
     */
    private String wxopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.senderName
     *
     * @mbggenerated
     */
    private String sendername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.senderPhone
     *
     * @mbggenerated
     */
    private Integer senderphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.senderAddressId
     *
     * @mbggenerated
     */
    private Integer senderaddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.senderAddressDetail
     *
     * @mbggenerated
     */
    private String senderaddressdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.recipientName
     *
     * @mbggenerated
     */
    private String recipientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.recipientPhone
     *
     * @mbggenerated
     */
    private Integer recipientphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.recipientAddressId
     *
     * @mbggenerated
     */
    private Integer recipientaddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.recipientAddressDetail
     *
     * @mbggenerated
     */
    private String recipientaddressdetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.weight
     *
     * @mbggenerated
     */
    private Integer weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.amount
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxorder.isable
     *
     * @mbggenerated
     */
    private Integer isable;
    
    private Date createTime;
    
    private Date updateTime;
    

    /** 
	* 获取createTime 
	* @return createTime createTime 
	*/
	public Date getCreateTime() {
		return createTime;
	}
	

	/** 
	* 设置createTime 
	* @param createTime createTime 
	*/
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	

	/** 
	* 获取updateTime 
	* @return updateTime updateTime 
	*/
	public Date getUpdateTime() {
		return updateTime;
	}
	

	/** 
	* 设置updateTime 
	* @param updateTime updateTime 
	*/
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.orderId
     *
     * @return the value of wxorder.orderId
     *
     * @mbggenerated
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.orderId
     *
     * @param orderid the value for wxorder.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.wxopenId
     *
     * @return the value of wxorder.wxopenId
     *
     * @mbggenerated
     */
    public String getWxopenid() {
        return wxopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.wxopenId
     *
     * @param wxopenid the value for wxorder.wxopenId
     *
     * @mbggenerated
     */
    public void setWxopenid(String wxopenid) {
        this.wxopenid = wxopenid == null ? null : wxopenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.senderName
     *
     * @return the value of wxorder.senderName
     *
     * @mbggenerated
     */
    public String getSendername() {
        return sendername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.senderName
     *
     * @param sendername the value for wxorder.senderName
     *
     * @mbggenerated
     */
    public void setSendername(String sendername) {
        this.sendername = sendername == null ? null : sendername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.senderPhone
     *
     * @return the value of wxorder.senderPhone
     *
     * @mbggenerated
     */
    public Integer getSenderphone() {
        return senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.senderPhone
     *
     * @param senderphone the value for wxorder.senderPhone
     *
     * @mbggenerated
     */
    public void setSenderphone(Integer senderphone) {
        this.senderphone = senderphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.senderAddressId
     *
     * @return the value of wxorder.senderAddressId
     *
     * @mbggenerated
     */
    public Integer getSenderaddressid() {
        return senderaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.senderAddressId
     *
     * @param senderaddressid the value for wxorder.senderAddressId
     *
     * @mbggenerated
     */
    public void setSenderaddressid(Integer senderaddressid) {
        this.senderaddressid = senderaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.senderAddressDetail
     *
     * @return the value of wxorder.senderAddressDetail
     *
     * @mbggenerated
     */
    public String getSenderaddressdetail() {
        return senderaddressdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.senderAddressDetail
     *
     * @param senderaddressdetail the value for wxorder.senderAddressDetail
     *
     * @mbggenerated
     */
    public void setSenderaddressdetail(String senderaddressdetail) {
        this.senderaddressdetail = senderaddressdetail == null ? null : senderaddressdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.recipientName
     *
     * @return the value of wxorder.recipientName
     *
     * @mbggenerated
     */
    public String getRecipientname() {
        return recipientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.recipientName
     *
     * @param recipientname the value for wxorder.recipientName
     *
     * @mbggenerated
     */
    public void setRecipientname(String recipientname) {
        this.recipientname = recipientname == null ? null : recipientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.recipientPhone
     *
     * @return the value of wxorder.recipientPhone
     *
     * @mbggenerated
     */
    public Integer getRecipientphone() {
        return recipientphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.recipientPhone
     *
     * @param recipientphone the value for wxorder.recipientPhone
     *
     * @mbggenerated
     */
    public void setRecipientphone(Integer recipientphone) {
        this.recipientphone = recipientphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.recipientAddressId
     *
     * @return the value of wxorder.recipientAddressId
     *
     * @mbggenerated
     */
    public Integer getRecipientaddressid() {
        return recipientaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.recipientAddressId
     *
     * @param recipientaddressid the value for wxorder.recipientAddressId
     *
     * @mbggenerated
     */
    public void setRecipientaddressid(Integer recipientaddressid) {
        this.recipientaddressid = recipientaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.recipientAddressDetail
     *
     * @return the value of wxorder.recipientAddressDetail
     *
     * @mbggenerated
     */
    public String getRecipientaddressdetail() {
        return recipientaddressdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.recipientAddressDetail
     *
     * @param recipientaddressdetail the value for wxorder.recipientAddressDetail
     *
     * @mbggenerated
     */
    public void setRecipientaddressdetail(String recipientaddressdetail) {
        this.recipientaddressdetail = recipientaddressdetail == null ? null : recipientaddressdetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.weight
     *
     * @return the value of wxorder.weight
     *
     * @mbggenerated
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.weight
     *
     * @param weight the value for wxorder.weight
     *
     * @mbggenerated
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.amount
     *
     * @return the value of wxorder.amount
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.amount
     *
     * @param amount the value for wxorder.amount
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.status
     *
     * @return the value of wxorder.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.status
     *
     * @param status the value for wxorder.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.username
     *
     * @return the value of wxorder.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.username
     *
     * @param username the value for wxorder.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxorder.isable
     *
     * @return the value of wxorder.isable
     *
     * @mbggenerated
     */
    public Integer getIsable() {
        return isable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxorder.isable
     *
     * @param isable the value for wxorder.isable
     *
     * @mbggenerated
     */
    public void setIsable(Integer isable) {
        this.isable = isable;
    }
}