package com.soecode.lyf.dao;

import java.util.List;

import com.soecode.lyf.common.Query;
import com.soecode.lyf.entity.OrderQuery;
import com.soecode.lyf.entity.WxOrder;

public interface WxOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated
     */
    int insert(WxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated
     */
    int insertSelective(WxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated
     */
    WxOrder selectByPrimaryKey(String orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxorder
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxOrder record);

	List<WxOrder> queryList(Query<OrderQuery> order);

	int count(Query<OrderQuery> order);
}